export const ENTITY_TYPE_LOOKUP: Record<string, string> = {
  BC: 'BC Company',
  CP: 'Cooperative',
  GP: 'General Partnership',
  S: 'Society',
  SP: 'Sole Proprietorship',
  A: 'Extraprovincial Company',
  B: 'Extraprovincial',
  BEN: 'Benefit Company',
  C: 'Continuation In',
  CC: 'BC Community Contribution Company',
  CS: 'Continued In Society',
  CUL: 'Continuation In as a BC ULC',
  EPR: 'Extraprovincial Registration',
  FI: 'Financial Institution',
  FOR: 'Foreign Registration',
  LIB: 'Public Library Association',
  LIC: 'Licensed (Extra-Pro)',
  LL: 'Limited Liability Partnership',
  LLC: 'Limited Liability Company',
  LP: 'Limited Partnership',
  MF: 'Miscellaneous Firm',
  PA: 'Private Act',
  PAR: 'Parish',
  QA: 'CO 1860',
  QB: 'CO 1862',
  QC: 'CO 1878',
  QD: 'CO 1890',
  QE: 'CO 1897',
  REG: 'Registration (Extra-pro)',
  ULC: 'BC Unlimited Liability Company',
  XCP: 'Extraprovincial Cooperative',
  XL: 'Extrapro Limited Liability Partnership',
  XP: 'Extraprovincial Limited Partnership',
  XS: 'Extraprovincial Society',
};
