apiVersion: v1
kind: Service
metadata:
  name: dev2-grants-backend
  labels:
    app: dev2-grants-backend
    app.kubernetes.io/part-of: dev2-unity-applicant-portal
  annotations:
    app.kubernetes.io/part-of: dev2-unity-applicant-portal
spec:
  selector:
    app: dev2-grants-backend
  ports:
    - protocol: TCP
      port: 5100
      targetPort: 5100
  type: ClusterIP